server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      port: 27017
      database: userdb

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

user_service:
  app:
    jwtSecret: userSecretKey